repos:
- repo: local
  hooks:
  - id: make-lint
    name: Lint Code
    entry: make lint
    language: system
    fail_fast: true
- repo: local
  hooks:
  - id: make-test
    name: Run Unit Tests
    entry: make test-no-cov
    language: system
    fail_fast: true
    stages: [push]