coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false
